In [1]:
%pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.

In [30]:
import pandas as pd
import numpy as np

In [ ]:
pd.__version__

'3.0.6'

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/bd/2a/14b3b17cd75cef4a1ee1af4234eb41cc1afe4103b98c2d80e8916abfd42b/pandas-3.0.6-cp312-cp312-win_amd64.whl.metadata
  Downloading pandas-3.0.6-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\reem\appdata\roaming\python\python312\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\reem\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Obtaining dependency information for tzdata from https://files.pythonhosted.org/packages/f9/bc/8737e8d54cf51106118039b83f485a4783112fab49ea9d044b234978a46e/tzdata-2026.4-py2.py3-none-any.whl.metadata
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\reem\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB 245.8 kB/s eta 0:00:40
   ---------------------------------------- 0.1/9.7 MB 297.7 kB/s eta 0:00:33
   ---------------------------------------- 0.1/9.7 MB 297.7 kB/s eta 0:00:33
   ---------------------------------------- 0.1/9.7 MB 286.7 kB/s eta 0:00:34
   ---------------------------------------- 0.1/9.7 MB 286.7 kB/s eta 0:00:34
   ---------------------------------------- 0.1/9.7 MB 228.2 kB/s eta 0:00:42
   ---------------------------------------- 0.1/9.7 MB 228.2 kB/s eta 0:00:42
   ---------------------------------------- 0.1/9.7 MB 242.7 kB/s eta 0:00:40
   ---------------------------------------- 0.1/9.7 MB 242.7 kB/s eta 0:00:40
   ---------------------------------------- 0.1/9.7 MB 242.7 kB/s eta 0:00:40
   ---------------------------------------- 0.1/9.7 MB 242.7 kB/s eta 0:00:40
    --------------------------------------- 0.1/9.7 MB 194.9 kB/s eta 0:00:49
    --------------------------------------- 0.1/9.7 MB 194.9 kB/s eta 0:00:49
    --------------------------------------- 0.1/9.7 MB 194.9 kB/s eta 0:00:49
    --------------------------------------- 0.1/9.7 MB 194.9 kB/s eta 0:00:49
    --------------------------------------- 0.1/9.7 MB 173.8 kB/s eta 0:00:55
    --------------------------------------- 0.1/9.7 MB 173.8 kB/s eta 0:00:55
    --------------------------------------- 0.1/9.7 MB 173.8 kB/s eta 0:00:55
    --------------------------------------- 0.1/9.7 MB 173.8 kB/s eta 0:00:55
    --------------------------------------- 0.1/9.7 MB 173.8 kB/s eta 0:00:55
    --------------------------------------- 0.1/9.7 MB 173.8 kB/s eta 0:00:55
    --------------------------------------- 0.2/9.7 MB 149.0 kB/s eta 0:01:04
    --------------------------------------- 0.2/9.7 MB 149.0 kB/s eta 0:01:04
    --------------------------------------- 0.2/9.7 MB 149.0 kB/s eta 0:01:04
    --------------------------------------- 0.2/9.7 MB 149.0 kB/s eta 0:01:04
    --------------------------------------- 0.2/9.7 MB 149.0 kB/s eta 0:01:04
    --------------------------------------- 0.2/9.7 MB 149.0 kB/s eta 0:01:04
    --------------------------------------- 0.2/9.7 MB 149.0 kB/s eta 0:01:04
    --------------------------------------- 0.2/9.7 MB 149.0 kB/s eta 0:01:04
    --------------------------------------- 0.2/9.7 MB 149.0 kB/s eta 0:01:04
    --------------------------------------- 0.2/9.7 MB 149.0 kB/s eta 0:01:04
    --------------------------------------- 0.2/9.7 MB 114.0 kB/s eta 0:01:24
    --------------------------------------- 0.2/9.7 MB 114.0 kB/s eta 0:01:24
    --------------------------------------- 0.2/9.7 MB 114.0 kB/s eta 0:01:24
    --------------------------------------- 0.2/9.7 MB 114.0 kB/s eta 0:01:24
    --------------------------------------- 0.2/9.7 MB 114.6 kB/s eta 0:01:23
    --------------------------------------- 0.2/9.7 MB 114.6 kB/s eta 0:01:23
    --------------------------------------- 0.2/9.7 MB 114.6 kB/s eta 0:01:23
    --------------------------------------- 0.2/9.7 MB 110.2 kB/s eta 0:01:26
    --------------------------------------- 0.2/9.7 MB 110.2 kB/s eta 0:01:26
    --------------------------------------- 0.2/9.7 MB 110.2 kB/s eta 0:01:26
    --------------------------------------- 0.2/9.7 MB 113.7 kB/s eta 0:01:23
    --------------------------------------- 0.2/9.7 MB 113.7 kB/s eta 0:01:23
    --------------------------------------- 0.2/9.7 MB 113.7 kB/s eta 0:01:23
    --------------------------------------- 0.2/9.7 MB 113.7 kB/s eta 0:01:23
    --------------------------------------- 0.2/9.7 MB 113.7 kB/s eta 0:01:23
   - -------------------------------------- 0.2/9.7 MB 112.5 kB/s eta 0:01:24
   - -------------------------------------- 0.2/9.7 MB 112.5 kB/s eta 0:01:24
   - -------------------------------------- 0.2/9.7 MB 112.5 kB/s eta 0:01:24
   - -------------------------------------- 0.2/9.7 MB 112.5 kB/s eta 0:01:24
   - -------------------------------------- 0.2/9.7 MB 112.5 kB/s eta 0:01:24
   - -------------------------------------- 0.3/9.7 MB 105.6 kB/s eta 0:01:30
   - -------------------------------------- 0.3/9.7 MB 105.6 kB/s eta 0:01:30
   - -------------------------------------- 0.3/9.7 MB 105.6 kB/s eta 0:01:30
   - -------------------------------------- 0.3/9.7 MB 105.6 kB/s eta 0:01:30
   - -------------------------------------- 0.3/9.7 MB 105.2 kB/s eta 0:01:30
   - -------------------------------------- 0.3/9.7 MB 105.2 kB/s eta 0:01:30
   - -------------------------------------- 0.3/9.7 MB 105.2 kB/s eta 0:01:30
   - -------------------------------------- 0.3/9.7 MB 105.2 kB/s eta 0:01:30
   - -------------------------------------- 0.3/9.7 MB 102.3 kB/s eta 0:01:32
   - -------------------------------------- 0.3/9.7 MB 102.3 kB/s eta 0:01:32
   - -------------------------------------- 0.3/9.7 MB 102.3 kB/s eta 0:01:32
   - -------------------------------------- 0.3/9.7 MB 102.3 kB/s eta 0:01:32
   - -------------------------------------- 0.3/9.7 MB 103.9 kB/s eta 0:01:31
   - -------------------------------------- 0.3/9.7 MB 103.9 kB/s eta 0:01:31
   - -------------------------------------- 0.3/9.7 MB 103.9 kB/s eta 0:01:31
   - -------------------------------------- 0.3/9.7 MB 106.4 kB/s eta 0:01:28
   - -------------------------------------- 0.3/9.7 MB 106.4 kB/s eta 0:01:28
   - -------------------------------------- 0.3/9.7 MB 106.4 kB/s eta 0:01:28
   - -------------------------------------- 0.3/9.7 MB 106.4 kB/s eta 0:01:28
   - -------------------------------------- 0.3/9.7 MB 106.4 kB/s eta 0:01:28
   - -------------------------------------- 0.3/9.7 MB 106.4 kB/s eta 0:01:28
   - -------------------------------------- 0.3/9.7 MB 100.3 kB/s eta 0:01:33
   - -------------------------------------- 0.3/9.7 MB 100.3 kB/s eta 0:01:33
   - -------------------------------------- 0.3/9.7 MB 100.3 kB/s eta 0:01:33
   - -------------------------------------- 0.3/9.7 MB 100.3 kB/s eta 0:01:33
   - -------------------------------------- 0.3/9.7 MB 100.3 kB/s eta 0:01:33
   - -------------------------------------- 0.3/9.7 MB 100.3 kB/s eta 0:01:33
   - -------------------------------------- 0.3/9.7 MB 100.3 kB/s eta 0:01:33
   - -------------------------------------- 0.4/9.7 MB 97.7 kB/s eta 0:01:36
   - -------------------------------------- 0.4/9.7 MB 97.7 kB/s eta 0:01:36
   - -------------------------------------- 0.4/9.7 MB 97.7 kB/s eta 0:01:36
   - -------------------------------------- 0.4/9.7 MB 97.7 kB/s eta 0:01:36
   - -------------------------------------- 0.4/9.7 MB 97.7 kB/s eta 0:01:36
   - -------------------------------------- 0.4/9.7 MB 94.0 kB/s eta 0:01:39
   - -------------------------------------- 0.4/9.7 MB 94.0 kB/s eta 0:01:39
   - -------------------------------------- 0.4/9.7 MB 94.0 kB/s eta 0:01:39
   - -------------------------------------- 0.4/9.7 MB 94.0 kB/s eta 0:01:39
   - -------------------------------------- 0.4/9.7 MB 95.1 kB/s eta 0:01:38
   - -------------------------------------- 0.4/9.7 MB 95.1 kB/s eta 0:01:38
   - -------------------------------------- 0.4/9.7 MB 95.1 kB/s eta 0:01:38
   - -------------------------------------- 0.4/9.7 MB 95.1 kB/s eta 0:01:38
   - -------------------------------------- 0.4/9.7 MB 95.1 kB/s eta 0:01:38
   - -------------------------------------- 0.4/9.7 MB 95.1 kB/s eta 0:01:38
   - -------------------------------------- 0.4/9.7 MB 94.0 kB/s eta 0:01:39
   - -------------------------------------- 0.4/9.7 MB 95.3 kB/s eta 0:01:37
   - -------------------------------------- 0.4/9.7 MB 95.3 kB/s eta 0:01:37
   - -------------------------------------- 0.4/9.7 MB 95.3 kB/s eta 0:01:37
   - -------------------------------------- 0.4/9.7 MB 95.3 kB/s eta 0:01:37
   - -------------------------------------- 0.4/9.7 MB 95.3 kB/s eta 0:01:37
   - -------------------------------------- 0.4/9.7 MB 95.6 kB/s eta 0:01:37
   - -------------------------------------- 0.4/9.7 MB 95.6 kB/s eta 0:01:37
   - -------------------------------------- 0.4/9.7 MB 95.6 kB/s eta 0:01:37
   - -------------------------------------- 0.5/9.7 MB 94.6 kB/s eta 0:01:38
   - -------------------------------------- 0.5/9.7 MB 94.6 kB/s eta 0:01:38
   - -------------------------------------- 0.5/9.7 MB 94.6 kB/s eta 0:01:38
   - -------------------------------------- 0.5/9.7 MB 94.6 kB/s eta 0:01:38
   - -------------------------------------- 0.5/9.7 MB 94.6 kB/s eta 0:01:38
   - -------------------------------------- 0.5/9.7 MB 94.8 kB/s eta 0:01:37
   - -------------------------------------- 0.5/9.7 MB 94.8 kB/s eta 0:01:37
   - -------------------------------------- 0.5/9.7 MB 94.8 kB/s eta 0:01:37
   - -------------------------------------- 0.5/9.7 MB 94.8 kB/s eta 0:01:37
   -- ------------------------------------- 0.5/9.7 MB 95.7 kB/s eta 0:01:36
   -- ------------------------------------- 0.5/9.7 MB 95.7 kB/s eta 0:01:36
   -- ------------------------------------- 0.5/9.7 MB 95.6 kB/s eta 0:01:36
   -- ------------------------------------- 0.5/9.7 MB 95.6 kB/s eta 0:01:36
   -- ------------------------------------- 0.5/9.7 MB 95.6 kB/s eta 0:01:36
   -- ------------------------------------- 0.5/9.7 MB 97.5 kB/s eta 0:01:34
   -- ------------------------------------- 0.5/9.7 MB 97.5 kB/s eta 0:01:34
   -- ------------------------------------- 0.5/9.7 MB 97.5 kB/s eta 0:01:34
   -- ------------------------------------- 0.5/9.7 MB 97.5 kB/s eta 0:01:34
   -- ------------------------------------- 0.6/9.7 MB 99.8 kB/s eta 0:01:32
   -- ------------------------------------- 0.6/9.7 MB 99.8 kB/s eta 0:01:32
   -- ------------------------------------- 0.6/9.7 MB 101.5 kB/s eta 0:01:30
   -- ------------------------------------- 0.6/9.7 MB 101.5 kB/s eta 0:01:30
   -- ------------------------------------- 0.6/9.7 MB 101.5 kB/s eta 0:01:30
   -- ------------------------------------- 0.6/9.7 MB 101.1 kB/s eta 0:01:30
   -- ------------------------------------- 0.6/9.7 MB 101.1 kB/s eta 0:01:30
   -- ------------------------------------- 0.6/9.7 MB 101.1 kB/s eta 0:01:30
   -- ------------------------------------- 0.6/9.7 MB 100.4 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 100.4 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 100.4 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 100.4 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 100.4 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 100.4 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 99.7 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 99.7 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 99.7 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 99.7 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 99.7 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 99.7 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 99.7 kB/s eta 0:01:31
   -- ------------------------------------- 0.6/9.7 MB 96.1 kB/s eta 0:01:35
   -- ------------------------------------- 0.6/9.7 MB 96.1 kB/s eta 0:01:35
   -- ------------------------------------- 0.6/9.7 MB 96.1 kB/s eta 0:01:35
   -- ------------------------------------- 0.6/9.7 MB 96.1 kB/s eta 0:01:35
   -- ------------------------------------- 0.6/9.7 MB 96.1 kB/s eta 0:01:35
   -- ------------------------------------- 0.6/9.7 MB 96.1 kB/s eta 0:01:35
   -- ------------------------------------- 0.6/9.7 MB 96.1 kB/s eta 0:01:35
   -- ------------------------------------- 0.6/9.7 MB 96.1 kB/s eta 0:01:35
   -- ------------------------------------- 0.6/9.7 MB 94.5 kB/s eta 0:01:36
   -- ------------------------------------- 0.6/9.7 MB 94.5 kB/s eta 0:01:36
   -- ------------------------------------- 0.6/9.7 MB 94.5 kB/s eta 0:01:36
   -- ------------------------------------- 0.6/9.7 MB 94.5 kB/s eta 0:01:36
   -- ------------------------------------- 0.6/9.7 MB 94.5 kB/s eta 0:01:36
   -- ------------------------------------- 0.6/9.7 MB 94.5 kB/s eta 0:01:36
   -- ------------------------------------- 0.6/9.7 MB 94.5 kB/s eta 0:01:36
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 93.4 kB/s eta 0:01:37
   -- ------------------------------------- 0.7/9.7 MB 88.2 kB/s eta 0:01:42
   -- ------------------------------------- 0.7/9.7 MB 88.2 kB/s eta 0:01:42
   -- ------------------------------------- 0.7/9.7 MB 88.2 kB/s eta 0:01:42
   -- ------------------------------------- 0.7/9.7 MB 88.2 kB/s eta 0:01:42
   -- ------------------------------------- 0.7/9.7 MB 88.2 kB/s eta 0:01:42
   -- ------------------------------------- 0.7/9.7 MB 88.2 kB/s eta 0:01:42
   -- ------------------------------------- 0.7/9.7 MB 88.2 kB/s eta 0:01:42
   -- ------------------------------------- 0.7/9.7 MB 88.2 kB/s eta 0:01:42
   -- ------------------------------------- 0.7/9.7 MB 88.2 kB/s eta 0:01:42
   -- ------------------------------------- 0.7/9.7 MB 87.6 kB/s eta 0:01:43
   -- ------------------------------------- 0.7/9.7 MB 87.6 kB/s eta 0:01:43
   -- ------------------------------------- 0.7/9.7 MB 87.6 kB/s eta 0:01:43
   -- ------------------------------------- 0.7/9.7 MB 87.6 kB/s eta 0:01:43
   -- ------------------------------------- 0.7/9.7 MB 87.6 kB/s eta 0:01:43
   -- ------------------------------------- 0.7/9.7 MB 87.6 kB/s eta 0:01:43
   -- ------------------------------------- 0.7/9.7 MB 87.6 kB/s eta 0:01:43
   --- ------------------------------------ 0.7/9.7 MB 89.0 kB/s eta 0:01:41
   --- ------------------------------------ 0.7/9.7 MB 89.0 kB/s eta 0:01:41
   --- ------------------------------------ 0.7/9.7 MB 89.0 kB/s eta 0:01:41
   --- ------------------------------------ 0.7/9.7 MB 89.0 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.6 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.6 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.6 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.6 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.6 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.7 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.7 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.7 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.7 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.7 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.7 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.7 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.7 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 88.7 kB/s eta 0:01:41
   --- ------------------------------------ 0.8/9.7 MB 86.0 kB/s eta 0:01:44
   --- ------------------------------------ 0.8/9.7 MB 86.0 kB/s eta 0:01:44
   --- ------------------------------------ 0.8/9.7 MB 86.0 kB/s eta 0:01:44
   --- ------------------------------------ 0.8/9.7 MB 86.0 kB/s eta 0:01:44
   --- ------------------------------------ 0.8/9.7 MB 86.0 kB/s eta 0:01:44
   --- ------------------------------------ 0.8/9.7 MB 86.0 kB/s eta 0:01:44
   --- ------------------------------------ 0.8/9.7 MB 86.0 kB/s eta 0:01:44
   --- ------------------------------------ 0.8/9.7 MB 86.0 kB/s eta 0:01:44
   --- ------------------------------------ 0.8/9.7 MB 86.0 kB/s eta 0:01:44
   --- ------------------------------------ 0.8/9.7 MB 84.9 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.9 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.9 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.9 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.9 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.9 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.4 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.4 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.4 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.4 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.4 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 84.4 kB/s eta 0:01:45
   --- ------------------------------------ 0.8/9.7 MB 82.9 kB/s eta 0:01:47
   --- ------------------------------------ 0.8/9.7 MB 82.9 kB/s eta 0:01:47
   --- ------------------------------------ 0.8/9.7 MB 82.9 kB/s eta 0:01:47
   --- ------------------------------------ 0.8/9.7 MB 82.9 kB/s eta 0:01:47
   --- ------------------------------------ 0.8/9.7 MB 82.9 kB/s eta 0:01:47
   --- ------------------------------------ 0.8/9.7 MB 82.9 kB/s eta 0:01:47
   --- ------------------------------------ 0.8/9.7 MB 82.9 kB/s eta 0:01:47
   --- ------------------------------------ 0.8/9.7 MB 82.9 kB/s eta 0:01:47
   --- ------------------------------------ 0.8/9.7 MB 82.9 kB/s eta 0:01:47
   --- ------------------------------------ 0.9/9.7 MB 82.3 kB/s eta 0:01:47
   --- ------------------------------------ 0.9/9.7 MB 82.3 kB/s eta 0:01:47
   --- ------------------------------------ 0.9/9.7 MB 82.3 kB/s eta 0:01:47
   --- ------------------------------------ 0.9/9.7 MB 82.3 kB/s eta 0:01:47
   --- ------------------------------------ 0.9/9.7 MB 82.3 kB/s eta 0:01:47
   --- ------------------------------------ 0.9/9.7 MB 82.3 kB/s eta 0:01:47

In [5]:
df=pd.read_csv('car_fuel_efficiency_2026.csv')

In [6]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
df.shape

(10000, 11)

In [8]:
df.fuel_type.describe()

count        10000
unique           3
top       Gasoline
freq          6913
Name: fuel_type, dtype: object

In [11]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [14]:
df[df['origin']=='Asia'].max()

model_year                         2024
origin                             Asia
fuel_type                        Hybrid
drivetrain             Rear-wheel drive
num_doors                             5
engine_displacement                3020
num_cylinders                         8
horsepower                        334.0
vehicle_weight                     5280
acceleration                       23.8
fuel_efficiency_mpg                41.2
dtype: object

In [15]:
df.horsepower.median()

np.float64(254.0)

In [ ]:
df.horsepower.mode()

np.float64(252.0)

In [18]:
df.horsepower.fillna(252.0)

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [19]:
df.horsepower.median()

np.float64(254.0)

In [22]:
df2=df[df['origin']=='Asia']

In [23]:
df2

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [54]:
arr=df2[['vehicle_weight','model_year']].head(n=7)
arr.shape

(7, 2)

In [55]:
X=arr.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [56]:
XTX=X.T@X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [57]:
XTX_inv=np.linalg.inv(XTX)

In [58]:
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [59]:
print("X shape:", X.shape)
print("X.T shape:", X.T.shape)
print("XTX shape:", XTX.shape)
print("XTX_inv shape:", XTX_inv.shape)
print("y shape:", y.shape)

X shape: (7, 2)
X.T shape: (2, 7)
XTX shape: (2, 2)
XTX_inv shape: (2, 2)
y shape: (7,)

In [60]:
w =XTX_inv @ X.T @ y

In [61]:
w.shape

(2,)

In [62]:
w.sum()

np.float64(0.36919696904925486)